---
#  _                 _       _                     ___            _        
# | |__   ___   ___ | |_ ___| |_ _ __ __ _ _ __   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \ / _ \| __/ __| __| '__/ _` | '_ \ / /| __/ _` / __| |/ / __|
# | |_) | (_) | (_) | |_\__ \ |_| | | (_| | |_) / / | || (_| \__ \   <\__ \
# |_.__/ \___/ \___/ \__|___/\__|_|  \__,_| .__/_/   \__\__,_|___/_|\_\___/
#                                         |_|                              
# boot-script
- name: boot-script | yum-cron should be started
  when: ansible_os_family == "RedHat"
  service:
    name:    "yum-cron"
    enabled: "yes"

- name: boot-script | yum-cron should be enabled
  when: ansible_os_family == "RedHat"
  service:
    name:  "yum-cron"
    state: "started"

