---
#  _                 _       _                     ___            _        
# | |__   ___   ___ | |_ ___| |_ _ __ __ _ _ __   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \ / _ \| __/ __| __| '__/ _` | '_ \ / /| __/ _` / __| |/ / __|
# | |_) | (_) | (_) | |_\__ \ |_| | | (_| | |_) / / | || (_| \__ \   <\__ \
# |_.__/ \___/ \___/ \__|___/\__|_|  \__,_| .__/_/   \__\__,_|___/_|\_\___/
#                                         |_|                              
# make-config
- name: make-config | {{ bootstrap.local.dir }} directory should be created
  file:
    path:  "{{ bootstrap.local.dir }}"
    mode:  "0775"
    owner: "root"
    group: "wheel"
    state: "directory"

- name: make-config | {{ bootstrap.local.src }} directory should be created
  file:
    path:  "{{ bootstrap.local.src }}"
    mode:  "0775"
    owner: "root"
    group: "wheel"
    state: "directory"

- name: make-config | /etc/motd should be deployed
  template:
    src:    "etc/motd.j2"
    dest:   "/etc/motd"
    backup: "no"


- name: make-config | Timezone should be configured (1)
  register: timezone
  ignore_errors: true
  changed_when: false
  shell: timedatectl status | grep "{{ bootstrap.timezone }}"

- name: make-config | Timezone should be configured (2)
  when: timezone.rc == 1
  shell: timedatectl set-timezone {{ bootstrap.timezone }}

- name: make-config | Deploy /etc/yum/yum-cron.conf
  notify: Restart yum-cron
  template:
    src:  "etc/yum/yum-cron.conf.j2"
    dest: "/etc/yum/yum-cron.conf"
    mode: "0644"

